# Generated by Django 2.1.7 on 2019-04-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(default='', max_length=23)),
                ('http', models.BooleanField(default=False, verbose_name='是否支持http代理')),
                ('https', models.BooleanField(default=False, verbose_name='是否支持https代理')),
                ('score', models.SmallIntegerField(default=100, verbose_name='分数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_exsist', models.BooleanField(default=True, verbose_name='是否存在')),
            ],
            options={
                'verbose_name': '代理池',
                'verbose_name_plural': '代理池',
                'db_table': 'df_proxy_pool',
            },
        ),
    ]
