# Generated by Django 2.1.7 on 2019-04-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='blog_id',
            field=models.CharField(default='cca2ba86', max_length=15, verbose_name='文章标识符'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='b564', max_length=10, verbose_name='用户uuid'),
        ),
    ]
